name: Pyweb

# on: push can also be used if you want to run the GitHub Actions pipeline when any branch is pushed to
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: python-lint
      uses: CyberZHG/github-action-python-lint@0.0.2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - run: |
        az appservice plan create -g Dev10 -n pywebplan
        az webapp create -g Dev10 -p pywebplan -n pyweb

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: pyweb
