# This is a basic workflow to help you get started with Actions

name: Pyweb

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - run: |
        az appservice plan create -g Dev10 -n pywebplan
        az webapp create -g Dev10 -p pywebplan -n pyweb

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: pyweb
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        # Enter the start up command. For ex. dotnet run or dotnet run
        # startup-command: python pyweb.py
